name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: |
          #echo "AWS_ACCESS_KEY_ID:" ${{ env.AWS_ACCESS_KEY_ID }}
          #echo "AWS_SECRET_ACCESS_KEY:" ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init
          
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Plan
        run: |
         terraform init -reconfigure
         terraform plan
        
      
  tf-apply:
    needs: build
    environment: Terraform Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -auto-approve

  docker-build-push:
    needs: tf-apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/setup-sam@v3
    - name: Build the Docker image
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 982081085352.dkr.ecr.eu-central-1.amazonaws.com
        docker build . --file Dockerfile --tag qlee94/tavernquest:latest
        docker push 982081085352.dkr.ecr.eu-central-1.amazonaws.com/tavernquest:latest
        
  tf-destroy:
    needs: docker-build-push
    environment: Terraform Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Terraform Destroy
      run: |
        terraform init -reconfigure
        terraform destroy -auto-approve
        

              
